anx: Add PRODUCT_BROKEN_VERIFY_USES_LIBRARIES
Fixes:
	error: mismatch in the <uses-library> tags between the build system and the manifest:
        - required libraries in build system: [org.apache.http.legacy]
                         vs. in the manifest: [org.apache.http.legacy]
        - optional libraries in build system: []
                         vs. in the manifest: [zxing.jar, cloud-common.jar, volley.jar]
        - tags in the manifest (packages/apps/ANXCamera/system/priv-app/ANXCamera/ANXCamera.apk):

Signed-off-by: 7Soldier <reg.fm4@gmail.com>